Name:           perl-Mail-Postfix-Postdrop
Version:        0.3
Release:        2%{?dist}
Summary:        Inject mails to a Postfix maildrop directory
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Mail-Postfix-Postdrop/
Source0:        http://www.cpan.org/authors/id/P/PM/PMAKHOLM/Mail-Postfix-Postdrop-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Email::Abstract)
BuildRequires:  perl(Email::Address)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)
BuildRequires:	perl(Module::Pluggable)
Requires:	postfix
Requires:       perl(Email::Abstract)
Requires:       perl(Email::Address)
Requires:       perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Bone::Mail::Postfix::Postdrop implements parts of postfix's postdrop(1)
utility. Using the functionel interface you can inject messages directly
into the maildrop queu and using the OOish interface you can control parts
of the process.

%prep
%setup -q -n Mail-Postfix-Postdrop-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

perldoc -t perlgpl > COPYING
perldoc -t perlartistic > Artistic

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README COPYING Artistic
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed May 28 2014 Curtis Doty <Curtis@GreenKey.net>
- add missing build dep (Module::Pluggable for make test)
- and uh...don't forget to require postfix doh!
- rebuild on old EL4

* Thu Nov 03 2011 Curtis Doty <Curtis@GreenKey.net> 0.3-1
- Specfile autogenerated by cpanspec 1.78.
