Name:           perl-SNMP-MIB-Compiler
Version:        0.06
Release:        1%{?dist}
Summary:        MIB Compiler supporting SMIv1 and SMIv2
License:        Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/SNMP-MIB-Compiler/
Source0:        http://www.cpan.org/authors/id/F/FT/FTASSIN/SNMP-MIB-Compiler-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Data::Compare)
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
SNMP::MIB::Compiler is a MIB compiler that fully supports    both SMI(v1)
and SMIv2. This module can be use to compile    MIBs (recursively or not)
or load already compiled MIBs for    later use.    Some tasks can be
performed by the resulting object such as :

%prep
%setup -q -n SNMP-MIB-Compiler-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf $RPM_BUILD_ROOT

%{__make} pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

# don't install script with Tk dependency
%{__rm} -f $RPM_BUILD_ROOT%{_bindir}/mibbrowser
# put in docs instead without x bit so we bypass dep checker
%{__chmod} a-x mibbrowser

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

perldoc -t perlartistic > Artistic

%check
%{__make} test

%clean
%{__rm} -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc mibbrowser mib-browser-1.gif README Artistic
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_bindir}/mib*

%changelog
* Sat Jul 05 2014 Curtis Doty <Curtis@GreenKey.net> 0.06-1
- Specfile autogenerated by cpanspec 1.78.
